To fix an
     RuntimeError: Missing host to link to! Please provide :host parameter or set default_url_options[:host]

exception, added these lines to the _load_config.rb initializer.